### ISSUE TITLE
Missing link to Deployment Guide

### ISSUE THREAD

**Issue by amynmerch** [shinesolutions/quickstart-aem-opencloud#1]
Hi there,

The link to the Deployment Guide in README.md is pointing to https://aws-quickstart.github.io/ instead of to the deployment guide.

Thank you

**Comment by mbloch1986** [comment]
Hi @amynmerch,

Thanks for your message. 

This repository is still under development, hence why there is no deployment guide available yet. 

If you need help to setup your AWS Environment in order to run AEM OpenCloud e.g. via quickstart-aem-opencloud, I recommend you to have a look into the existing documentation of [Packer-aem](https://github.com/shinesolutions/packer-aem/blob/master/docs/aws-resources.md) for the AMI creation and [aem-aws-stack-builder](https://github.com/shinesolutions/aem-aws-stack-builder) for the environment creation. 

Cheers
Michael

**Comment by mbloch1986** [comment]
Closing the issue as described above repository is still under development hence why no deployment guide is yet available.
